### PR TITLE
Add testcases that test the resulting png files

### PR DESCRIPTION
**Pull request by physikerwelt**
Since setup and installation of this package is non trivial I wrote those tests to test if the conversion actually works.

### CODE REVIEW

**Comment by physikerwelt** [comment]
CC @myfreeweb @dariusk  Comments are welcome.
The background for this tests are problems on ubuntu14 cf. https://github.com/wikimedia/MathJax-node/pull/18

**Comment by ctizen** [comment]
Looks good, but is it critical to remove node 0.10 from travis config? Did it cause any trouble?

**Comment by physikerwelt** [comment]
Yes. Node 0.10 can not compare buffers.
https://travis-ci.org/physikerwelt/node-rsvg/jobs/121673898
But I can try to find a workaround, since node 0.10 is still supported to october this year https://github.com/nodejs/LTS#lts_schedule

**Comment by valpackett** [comment]
Since this is just tests, we're not even breaking 0.10 compatibility in _the library_, right?

You can just not run _these_ tests on 0.10! Early return from the test if running on < 0.12.

**Comment by physikerwelt** [comment]
Yes, it's only about the tests. However, I fixed it and it now passes with all version
https://travis-ci.org/physikerwelt/node-rsvg/builds/121768663

**Comment by physikerwelt** [comment]
@myfreeweb anything else to do here?

**Comment by valpackett** [comment]
No?? I'm not the maintainer, by the way

**Comment by ctizen** [comment]
I'm sorry, I was quite busy for last two weeks. 
As it passed all travis tests, I think I can merge it.

**Pull request merged**
